### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by geeky01adarsh** [riti2409/Resources-for-preparation-Of-Placements#20]
Some of the links under C++ redirected me to a playlist that doesn't exist any longer. Please fix it.

**Comment by sanjeeban5644** [comment]
Hi! Can you mention the links which are having this issue? I would go through it then and try to fix it.

**Comment by geeky01adarsh** [comment]
I found it for-
[String](https://www.youtube.com/playlist?list=PL2q4fbVm1Ik6ThrYKCzgEpmaS_XWDGHjx)
